### ISSUE TITLE
Can your extensions work in TFS ?

### ISSUE THREAD

**Issue by shaibarlev** [mohitbagra/vsts-extensions#1]
Is there any technical barrier to enable the extensions worked in TFS ?

**Comment by mohitbagra** [comment]
Which one in particular? I tend to use the latest APIs in my extensions which may not be in all the versions of TFS.

**Comment by shaibarlev** [comment]
Checklist , ControlsLibrary , OneClick , RelatedWits and Library . The
BugBash would be nice too.
Since you might be supporting several VSTS/TFS versions , supporting
several API / API version  should be included.


Shai Bar-Lev

**Comment by mohitbagra** [comment]
"Library" is not an extension - its just a set of common stuff that all my extensions uses.
"Checklist" and "RelatedWit" extensions are already enabled for on-prem.

Unfortunately I cant release BugBashPro and OneClick extensions for on-prem yet because they use some latest VSTS rest APIs which are not enabled for on-prem yet. And if you look at the marketplace link for them, it says that they are only allowed for VSTS, not TFS
