### ISSUE TITLE
Enhancement: Save state and History entry for Checklists

### ISSUE THREAD

**Issue by cytron201** [mohitbagra/vsts-extensions#23]
Is it within the scope of the Core Client SDK for the checklist to be able to mark the Work Item as unsaved when changes were made, and enter the changes into the Work Item History to give some traceability on the changes?

**Comment by mohitbagra** [comment]
what do you mean "unsaved"? Once a work item is saved, there is no way to "unsave" it. 
About getting the changes in Work item history, it would only be possible if the checklist data is stored in a work item field. Right now the checklist data is stored outside of work items, so there is no history.
I have got the same feedback from a couple of other users too, so I'll start looking into how can users connect checklist with a work item field. So that any update to the checklist would go in work item history.

**Comment by cytron201** [comment]
For "Unsaved" I mean that currently when you make a change to the checklist, it does not change the save state of the work item. So if I open a work item and make a change only to the checklist, the work item does not enter the "unsaved state". But as you pointed out, that's due to not actually changing any work item fields.

Not sure if it'd be an efficient option, but perhaps outputting the data into a custom (but UI hidden) work item field would be viable (e.g. in the same way Backlog Priority field works). The issue would be how to best store the data in a format for which the history made sense when read. For example comma separated would serve the purpose but wouldn't be easily digested for the user.
