### ISSUE TITLE
Add ability to have conditional checklist based on Work Item Activity

### ISSUE THREAD

**Issue by jdasilva-huntswood** [mohitbagra/vsts-extensions#50]
Add ability to have conditional checklist based on Work Item Activity.

**Comment by mohitbagra** [comment]
Can you give me some use cases?

**Comment by jdasilva-huntswood** [comment]
Within a work item one can set an activity e.g. Development/Testing/Documentation. I would like if I could set standard checklists for each of these activities and the relevant one displayed on a work item dependent on the work item activity. I use the checklist as Definition of Done (per work item) and would like to only display the relevant checklist items based on the activity.

![image](https://user-images.githubusercontent.com/46450129/52502519-e23ca180-2bda-11e9-9833-ff80f5f00454.png)

**Comment by Ramanean** [comment]
Is this possible? would love to have this one on AzureDevOps

**Comment by mohitbagra** [comment]
I really dont want to add a lot of complexities to the extension. This is meant to be a simple quick and dirty way of managing checklist items. This scenario is very specific to your use case. There would be other customers who would want to have the same functionality but instead of Activity field, using State (or any other) field. If you really need this, you can fork the repo and change it to fit your needs and publish it as a new private extension.
